language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
  - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
  - pip install tox


matrix:
  include:
    - python: 3.6
      env:
       - TOX_ENV=py26-django_stable
    - python: 3.7
      env:
        - TOX_ENV=py37-django_stable
    - python: 3.8
      env:
        - TOX_ENV=py38-django_stable

services: mongodb

before_script:
  - mongo --version

script:
  - tox -e $TOX_ENV

